apiVersion: v2
name: wiki-chart
description: Helm chart for Wikipedia-like API system
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 12.0.0
    repository: "https://charts.bitnami.com/bitnami"
  - name: prometheus
    version: 28.6.1   
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: 10.3.0
    repository: "https://grafana.github.io/helm-charts"
